/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.project.starter;

//import java.util.System;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    //System.out.println("Hello World");
    //ArrayList<Integer> al = new ArrayList<>();
    
  }
}
